### ISSUE TITLE
Using reselect (state selectors, derived data)

### ISSUE THREAD

**Issue by ugros** [jumpsuit/jumpstate#41]
Hello,

I recently started using jumpstate. The first problem I encountered was lack of selectors.

Have you considered Reselect: https://github.com/reactjs/reselect integration?
Is there some other way to use selectors? Have anyone came up with a working solution?

If so, please provide us with an idiomatic way to use them (and consider adding it to the documentation/examples).

Thanks!

**Comment by FoxxMD** [comment]
@ugros Why did you close this? Did you find a solution for using reselect?

**Comment by tannerlinsley** [comment]
Sorry. The reason for closing that selectors do currently work in jumpstate
and there are no immediate plans to abstract them or ingest them into
jumpstate

**Comment by ugros** [comment]
The problem was that I had wrong understanding of what reselect selectors are. I thought they are similar to computed properties (from mobx or vue.js). But they are conceptually different. Anyways, if there was a way to implement something similar to computed properties to jumpstate, I would definitely give it a try ;) (even tho I know that's basically impossible without using observables)

**Comment by tannerlinsley** [comment]
No you are correct, they are computed/derived variables. Because
react-redux doesn’t work with observables (and instead uses immutable
change detection), reselect helps in computing derived data while still
playing nice with react-redux’s internal change detection (which out of the
box is basically a shallow object comparison between the previous and next
results of `mapStateToProps`).  Use reselect.  I promise you will love it
after you get used to it.
